GCP_PROJECT_ID: letsgodb
FIREBASE_PROJECT_ID: letsgodb
FIREBASE_ADMIN_ROLE: admin
ENVIRONMENT: production
CLOUD_SQL_CONNECTION_NAME: letsgodb:us-central1:free-trial-first-project
GCS_BUCKET_NAME: letsgosa-package-images
GCS_PUBLIC_BASE_URL: https://storage.googleapis.com/letsgosa-package-images
LETSGOSA_CORS_ALLOW_ORIGINS: https://letsgodb.web.app,https://letsgodb.firebaseapp.com
